config/routes.rb
TicTacToe::Application.routes.draw do
  root :to => 'Games#index'

  resources :boxes
  get '/boxes/:id/set_status/:status' => 'Boxes#set_status', :as => :set_status_box

  resources :games
  get '/games/:id/reset' => 'Games#reset', :as => :reset_game

end

app/models/arry.rb
class Array
  def check_works
    puts "works"
  end
end

app/models/box.rb
class Box < ActiveRecord::Base
  attr_accessible :name, :game_id, :status

  belongs_to :game
end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :name


  has_many :boxes

  def check_win
    statuses = self.boxes.sort.collect { |box| box.status }
    if [statuses[0], statuses[1], statuses[2]].all_equal_and_present?
      return statuses[0]
    elsif [statuses[3], statuses[4], statuses[5]].all_equal_and_present?
      return statuses[3]
    elsif [statuses[6], statuses[7], statuses[8]].all_equal_and_present?
      return statuses[6]
    elsif [statuses[0], statuses[3], statuses[6]].all_equal_and_present?
      return statuses[0]
    elsif [statuses[1], statuses[4], statuses[7]].all_equal_and_present?
      return statuses[1]
    elsif [statuses[2], statuses[5], statuses[8]].all_equal_and_present?
      return statuses[2]
    elsif [statuses[0], statuses[4], statuses[8]].all_equal_and_present?
      return statuses[0]
    elsif [statuses[2], statuses[4], statuses[6]].all_equal_and_present?
      return statuses[2]
    elsif statuses.exclude? nil
      return "cats_game"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  # GET /boxes
  # GET /boxes.json
  def index
    @boxes = Box.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @boxes }
    end
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
    @box = Box.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @box }
    end
  end

  # GET /boxes/new
  # GET /boxes/new.json
  def new
    @box = Box.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @box }
    end
  end

  # GET /boxes/1/edit
  def edit
    @box = Box.find(params[:id])
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = Box.new(params[:box])

    respond_to do |format|
      if @box.save
        format.html { redirect_to boxes_url, notice: 'Box was successfully created.' }
        format.json { render json: @box, status: :created, location: @box }
      else
        format.html { render action: "new" }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boxes/1
  # PUT /boxes/1.json
  def update
    @box = Box.find(params[:id])

    respond_to do |format|
      if @box.update_attributes(params[:box])
        format.html { redirect_to @box, notice: 'Box was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box = Box.find(params[:id])
    @box.destroy

    respond_to do |format|
      format.html { redirect_to boxes_url }
      format.json { head :no_content }
    end
  end

  def set_status
    box = Box.find(params[:id])
    game = box.game
    box.status = params[:status]
    box.save
    game.move_counter += 1
    game.save
    redirect_to box.game
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])
    @boxes = @game.boxes.sort

    @check_win = @game.check_win

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new



    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])
    @game.move_counter = 0

    respond_to do |format|
        if @game.save
          9.times do
          b = Box.create(:name => "Game #{@game.id} box",
                          :game_id => @game.id,
                          :status => nil)
        end
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  def reset
    game = Game.find(params[:id])
    game.boxes.each do |box|
      box.status = nil
      box.save
    end
    redirect_to game
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/boxes/_form.html.erb
<%= form_for(@box) do |f| %>
  <% if @box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@box.errors.count, "error") %> prohibited this box from being saved:</h2>

      <ul>
      <% @box.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :game_id %><br />
    <%= f.collection_select :game_id, Game.all, :id, :id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boxes/edit.html.erb
<h1>Editing box</h1>

<%= render 'form' %>

<%= link_to 'Show', @box %> |
<%= link_to 'Back', boxes_path %>

app/views/boxes/index.html.erb
<h1>Listing boxes</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @boxes.each do |box| %>
  <tr>
    <td><%= box.name %></td>
    <td><%= link_to 'Show', box %></td>
    <td><%= link_to 'Edit', edit_box_path(box) %></td>
    <td><%= link_to 'Destroy', box, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Box', new_box_path %>

app/views/boxes/new.html.erb
<h1>New box</h1>

<%= render 'form' %>

<%= link_to 'Back', boxes_path %>

app/views/boxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @box.name %>
</p>


<%= link_to 'Edit', edit_box_path(@box) %> |
<%= link_to 'Back', boxes_path %>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>added change</h1>
<h1>Listing games</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.name %></td>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<div id='game-instructions'>
  <% if @check_win == 'cats_game' %>
    <h2 id='game-outcome'>Cat's game! (=^･^=)</h2>
  <% elsif @check_win %>
    <h2 id='game-outcome'>
      <%= "#{@check_win.capitalize} Wins!" %>
    </h2>
  <% else %>
    <h2>Click on a square to start playing</h2>
  <% end %>
    <%= link_to 'Reset Game', reset_game_path(@game.id) %>
</div>



<% rows = 3 %>
<table id="tic-tac-toe-board">
<% n = 1 %>
<% rows.times do %>
  <tr>
    <% rows.times do %>
      <% box = @boxes[n-1] %>

      <td id="cell<%= n %>">
        <% if box.status == nil %>
          <% if @game.move_counter.even? %>
            <%= link_to(image_tag('white_box.jpg', :size => '50x50'), set_status_box_path(box.id, 'x')) %>
          <% else %>
            <%= link_to(image_tag('white_box.jpg', :size => '50x50'), set_status_box_path(box.id, 'o')) %>
          <% end %>
        <% elsif box.status == 'x' %>
          <%= image_tag('x.jpeg', :size => '50x50') %>
        <% else %>
          <%= image_tag('o.png', :size => '50x50') %>
        <% end %>
      </td>
      <% n +=1  %>
    <% end %>
  </tr>
<% end  %>
</table>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TicTacToe</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>